/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./media-keys.xml -p ManagerInterface
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MANAGERINTERFACE_H
#define MANAGERINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.ukui.SettingsDaemon.MediaKeys
 */
class MediaManagerDBus: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ukui.SettingsDaemon.MediaKeys"; }

public:
    MediaManagerDBus(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~MediaManagerDBus();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> grabMediaPlayerKeys()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("grabMediaPlayerKeys"), argumentList);
    }

    inline QDBusPendingReply<bool> releaseMediaPlayerKeys()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("releaseMediaPlayerKeys"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void mediaPlayerKeyPressed(const QString &application, const QString &key);
};

#endif
